From f6b6ac04a6b955e7c3131647f48b3ef724cafe51 Mon Sep 17 00:00:00 2001
From: jenisys <jenisys@users.noreply.github.com>
Date: Mon, 12 Oct 2020 21:52:25 +0200
Subject: [PATCH] Add support for python3.9 (by using active-tags).

---
 features/step.async_steps.feature | 21 +++++++++++++++++++++
 issue.features/issue0330.feature  |  6 ++++++
 issue.features/issue0446.feature  |  4 ++++
 issue.features/issue0457.feature  |  5 +++++
 issue.features/issue0657.feature  |  3 +++
 5 files changed, 39 insertions(+)

diff --git a/features/step.async_steps.feature b/features/step.async_steps.feature
index 3a18fa9..06709d9 100644
--- a/features/step.async_steps.feature
+++ b/features/step.async_steps.feature
@@ -32,6 +32,9 @@ Feature: Async-Test Support (async-step, ...)
 
     @use.with_python.version=3.5
     @use.with_python.version=3.6
+    @use.with_python.version=3.7
+    @use.with_python.version=3.8
+    @use.with_python.version=3.9
     Scenario: Use async-step with @async_run_until_complete (async)
       Given a new working directory
       And a file named "features/steps/async_steps35.py" with:
@@ -63,6 +66,9 @@ Feature: Async-Test Support (async-step, ...)
     @use.with_python.version=3.4
     @use.with_python.version=3.5
     @use.with_python.version=3.6
+    @use.with_python.version=3.7
+    @use.with_python.version=3.8
+    @use.with_python.version=3.9
     Scenario: Use async-step with @async_run_until_complete (@coroutine)
       Given a new working directory
       And a file named "features/steps/async_steps34.py" with:
@@ -93,6 +99,9 @@ Feature: Async-Test Support (async-step, ...)
 
     @use.with_python.version=3.5
     @use.with_python.version=3.6
+    @use.with_python.version=3.7
+    @use.with_python.version=3.8
+    @use.with_python.version=3.9
     Scenario: Use @async_run_until_complete(timeout=...) and TIMEOUT occurs (async)
       Given a new working directory
       And a file named "features/steps/async_steps_timeout35.py" with:
@@ -128,6 +137,9 @@ Feature: Async-Test Support (async-step, ...)
 
     @use.with_python.version=3.5
     @use.with_python.version=3.6
+    @use.with_python.version=3.7
+    @use.with_python.version=3.8
+    @use.with_python.version=3.9
     @async_step_fails
     Scenario: Use @async_run_until_complete and async-step fails
       Given a new working directory
@@ -170,6 +182,9 @@ Feature: Async-Test Support (async-step, ...)
 
     @use.with_python.version=3.5
     @use.with_python.version=3.6
+    @use.with_python.version=3.7
+    @use.with_python.version=3.8
+    @use.with_python.version=3.9
     @async_step_fails
     Scenario: Use @async_run_until_complete and async-step raises error
       Given a new working directory
@@ -213,6 +228,9 @@ Feature: Async-Test Support (async-step, ...)
     @use.with_python.version=3.4
     @use.with_python.version=3.5
     @use.with_python.version=3.6
+    @use.with_python.version=3.7
+    @use.with_python.version=3.8
+    @use.with_python.version=3.9
     Scenario: Use @async_run_until_complete(timeout=...) and TIMEOUT occurs (@coroutine)
       Given a new working directory
       And a file named "features/steps/async_steps_timeout34.py" with:
@@ -250,6 +268,9 @@ Feature: Async-Test Support (async-step, ...)
     @use.with_python.version=3.4
     @use.with_python.version=3.5
     @use.with_python.version=3.6
+    @use.with_python.version=3.7
+    @use.with_python.version=3.8
+    @use.with_python.version=3.9
     Scenario: Use async-dispatch and async-collect concepts
       Given a new working directory
       And a file named "features/steps/async_dispatch_steps.py" with:
diff --git a/issue.features/issue0330.feature b/issue.features/issue0330.feature
index 81cb6e2..be4d378 100644
--- a/issue.features/issue0330.feature
+++ b/issue.features/issue0330.feature
@@ -71,6 +71,7 @@ Feature: Issue #330: Skipped scenarios are included in junit reports when --no-s
 
 
   @not.with_python.version=3.8
+  @not.with_python.version=3.9
   Scenario: Junit report for skipped feature is created with --show-skipped
     When I run "behave --junit -t @tag1 --show-skipped @alice_and_bob.featureset"
     Then it should pass with:
@@ -85,6 +86,7 @@ Feature: Issue #330: Skipped scenarios are included in junit reports when --no-s
       """
 
   @use.with_python.version=3.8
+  @use.with_python.version=3.9
   Scenario: Junit report for skipped feature is created with --show-skipped
     When I run "behave --junit -t @tag1 --show-skipped @alice_and_bob.featureset"
     Then it should pass with:
@@ -101,6 +103,7 @@ Feature: Issue #330: Skipped scenarios are included in junit reports when --no-s
       # <testsuite errors="0" failures="0" name="bob.Bob" skipped="1" tests="1" time="0.0">
 
   @not.with_python.version=3.8
+  @not.with_python.version=3.9
   Scenario: Junit report for skipped scenario is neither shown nor counted with --no-skipped
     When I run "behave --junit -t @tag1 --no-skipped"
     Then it should pass with:
@@ -121,6 +124,7 @@ Feature: Issue #330: Skipped scenarios are included in junit reports when --no-s
     And note that "Charly2 is the skipped scenarion in charly.feature"
 
   @use.with_python.version=3.8
+  @use.with_python.version=3.9
   Scenario: Junit report for skipped scenario is neither shown nor counted with --no-skipped
     When I run "behave --junit -t @tag1 --no-skipped"
     Then it should pass with:
@@ -144,6 +148,7 @@ Feature: Issue #330: Skipped scenarios are included in junit reports when --no-s
 
 
   @not.with_python.version=3.8
+  @not.with_python.version=3.9
   Scenario: Junit report for skipped scenario is shown and counted with --show-skipped
     When I run "behave --junit -t @tag1 --show-skipped"
     Then it should pass with:
@@ -165,6 +170,7 @@ Feature: Issue #330: Skipped scenarios are included in junit reports when --no-s
 
 
   @use.with_python.version=3.8
+  @use.with_python.version=3.9
   Scenario: Junit report for skipped scenario is shown and counted with --show-skipped
     When I run "behave --junit -t @tag1 --show-skipped"
     Then it should pass with:
diff --git a/issue.features/issue0446.feature b/issue.features/issue0446.feature
index 901bdec..12de37a 100644
--- a/issue.features/issue0446.feature
+++ b/issue.features/issue0446.feature
@@ -59,6 +59,7 @@ Feature: Issue #446 -- Support scenario hook-errors with JUnitReporter
         """
 
     @not.with_python.version=3.8
+    @not.with_python.version=3.9
     Scenario: Hook error in before_scenario()
       When I run "behave -f plain --junit features/before_scenario_failure.feature"
       Then it should fail with:
@@ -88,6 +89,7 @@ Feature: Issue #446 -- Support scenario hook-errors with JUnitReporter
 
 
     @use.with_python.version=3.8
+    @use.with_python.version=3.9
     Scenario: Hook error in before_scenario()
       When I run "behave -f plain --junit features/before_scenario_failure.feature"
       Then it should fail with:
@@ -121,6 +123,7 @@ Feature: Issue #446 -- Support scenario hook-errors with JUnitReporter
 
 
     @not.with_python.version=3.8
+    @not.with_python.version=3.9
     Scenario: Hook error in after_scenario()
       When I run "behave -f plain --junit features/after_scenario_failure.feature"
       Then it should fail with:
@@ -152,6 +155,7 @@ Feature: Issue #446 -- Support scenario hook-errors with JUnitReporter
 
 
     @use.with_python.version=3.8
+    @use.with_python.version=3.9
     Scenario: Hook error in after_scenario()
       When I run "behave -f plain --junit features/after_scenario_failure.feature"
       Then it should fail with:
diff --git a/issue.features/issue0457.feature b/issue.features/issue0457.feature
index 46f96e9..6d2f48f 100644
--- a/issue.features/issue0457.feature
+++ b/issue.features/issue0457.feature
@@ -25,6 +25,7 @@ Feature: Issue #457 -- Double-quotes in error messages of JUnit XML reports
 
 
     @not.with_python.version=3.8
+    @not.with_python.version=3.9
     Scenario: Use failing assertation in a JUnit XML report
       Given a file named "features/fails1.feature" with:
         """
@@ -46,6 +47,7 @@ Feature: Issue #457 -- Double-quotes in error messages of JUnit XML reports
         """
 
     @use.with_python.version=3.8
+    @use.with_python.version=3.9
     Scenario: Use failing assertation in a JUnit XML report
       Given a file named "features/fails1.feature" with:
         """
@@ -70,6 +72,7 @@ Feature: Issue #457 -- Double-quotes in error messages of JUnit XML reports
 
 
     @not.with_python.version=3.8
+    @not.with_python.version=3.9
     Scenario: Use exception in a JUnit XML report
       Given a file named "features/fails2.feature" with:
         """
@@ -90,7 +93,9 @@ Feature: Issue #457 -- Double-quotes in error messages of JUnit XML reports
         <error message="My name is &quot;Bob&quot; and &lt;here&gt; I am"
         """
 
+
     @use.with_python.version=3.8
+    @use.with_python.version=3.9
     Scenario: Use exception in a JUnit XML report
       Given a file named "features/fails2.feature" with:
         """
diff --git a/issue.features/issue0657.feature b/issue.features/issue0657.feature
index f667893..aeaefd2 100644
--- a/issue.features/issue0657.feature
+++ b/issue.features/issue0657.feature
@@ -5,6 +5,9 @@ Feature: Issue #657 -- Allow async steps with timeouts to fail when they raise e
 
     @use.with_python.version=3.5
     @use.with_python.version=3.6
+    @use.with_python.version=3.7
+    @use.with_python.version=3.8
+    @use.with_python.version=3.9
     @async_step_fails
     Scenario: Use @async_run_until_complete and async-step fails
       Given a new working directory
